svr_list:
  - routeragent
  - gatesvr
  - lobbysvr

gate_listen_tcp: "0.0.0.0:5555"
gate_listen_ws: "0.0.0.0:5556"
routeragent_sock_path: "/tmp/routeragent/ra.sock"
routeragent_listen_addr: "127.0.0.1:7100"
cluster_name: "gameserver"
cluster_env: "dev"
etcd_endpoint_1: "http://localhost:2379"
etcd_endpoint_2: "http://localhost:2479"
etcd_endpoint_3: "http://localhost:2579"
redis_host: "localhost"
redis_port_1: 6379
redis_port_2: 6380
redis_port_3: 6381
redis_port_4: 6382
redis_port_5: 6383
redis_port_6: 6384
log_dir: "../log"
REDIS_PWD: "redisCluster123"
MONGO_URI: "mongodb://admin:mongoCluster123@localhost:27017/?authSource=admin"
mongo_database: "admin"
