syntax = "proto3";

package config;

import "config/schema/options.proto";

option go_package = "project/config/gen/server/gatesvr;gatesvr";

// GatesvrConfig 网关服主配置。
message GatesvrConfig {
  option (config.root) = true;
  option (config.server) = "gatesvr";

  string listen_tcp = 1 [(config.required) = true, (config.env) = true];
  string listen_ws = 2 [(config.required) = true, (config.env) = true];
  int32 max_conn = 3 [(config.required) = true];
  int32 heartbeat_sec = 4 [(config.required) = true, (config.reload) = true];
  string routeragent_sock_path = 5 [(config.required) = true, (config.env) = true];
}
