// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: protocol/handler/lobby_handler.proto

package handlerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "project/protocol/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CS_Ping_Req struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CS_Ping_Req) Reset() {
	*x = CS_Ping_Req{}
	mi := &file_protocol_handler_lobby_handler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CS_Ping_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS_Ping_Req) ProtoMessage() {}

func (x *CS_Ping_Req) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_handler_lobby_handler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS_Ping_Req.ProtoReflect.Descriptor instead.
func (*CS_Ping_Req) Descriptor() ([]byte, []int) {
	return file_protocol_handler_lobby_handler_proto_rawDescGZIP(), []int{0}
}

func (x *CS_Ping_Req) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type SC_Pong_Rsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SC_Pong_Rsp) Reset() {
	*x = SC_Pong_Rsp{}
	mi := &file_protocol_handler_lobby_handler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SC_Pong_Rsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SC_Pong_Rsp) ProtoMessage() {}

func (x *SC_Pong_Rsp) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_handler_lobby_handler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SC_Pong_Rsp.ProtoReflect.Descriptor instead.
func (*SC_Pong_Rsp) Descriptor() ([]byte, []int) {
	return file_protocol_handler_lobby_handler_proto_rawDescGZIP(), []int{1}
}

func (x *SC_Pong_Rsp) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_protocol_handler_lobby_handler_proto protoreflect.FileDescriptor

const file_protocol_handler_lobby_handler_proto_rawDesc = "" +
	"\n" +
	"$protocol/handler/lobby_handler.proto\x12\x10protocol.handler\x1a\x1dprotocol/common/options.proto\",\n" +
	"\vCS_Ping_Req\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text:\t\x98\xb5\x18\x86\x10\xa0\xb5\x18\x01\"(\n" +
	"\vSC_Pong_Rsp\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text:\x05\x98\xb5\x18\x87\x102^\n" +
	"\fLobbyHandler\x12D\n" +
	"\x04Ping\x12\x1d.protocol.handler.CS_Ping_Req\x1a\x1d.protocol.handler.SC_Pong_Rsp\x1a\b\x88\xb5\x18\x00\x90\xb5\x18\x02B$Z\"project/protocol/handler;handlerpbb\x06proto3"

var (
	file_protocol_handler_lobby_handler_proto_rawDescOnce sync.Once
	file_protocol_handler_lobby_handler_proto_rawDescData []byte
)

func file_protocol_handler_lobby_handler_proto_rawDescGZIP() []byte {
	file_protocol_handler_lobby_handler_proto_rawDescOnce.Do(func() {
		file_protocol_handler_lobby_handler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_handler_lobby_handler_proto_rawDesc), len(file_protocol_handler_lobby_handler_proto_rawDesc)))
	})
	return file_protocol_handler_lobby_handler_proto_rawDescData
}

var file_protocol_handler_lobby_handler_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protocol_handler_lobby_handler_proto_goTypes = []any{
	(*CS_Ping_Req)(nil), // 0: protocol.handler.CS_Ping_Req
	(*SC_Pong_Rsp)(nil), // 1: protocol.handler.SC_Pong_Rsp
}
var file_protocol_handler_lobby_handler_proto_depIdxs = []int32{
	0, // 0: protocol.handler.LobbyHandler.Ping:input_type -> protocol.handler.CS_Ping_Req
	1, // 1: protocol.handler.LobbyHandler.Ping:output_type -> protocol.handler.SC_Pong_Rsp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protocol_handler_lobby_handler_proto_init() }
func file_protocol_handler_lobby_handler_proto_init() {
	if File_protocol_handler_lobby_handler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_handler_lobby_handler_proto_rawDesc), len(file_protocol_handler_lobby_handler_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protocol_handler_lobby_handler_proto_goTypes,
		DependencyIndexes: file_protocol_handler_lobby_handler_proto_depIdxs,
		MessageInfos:      file_protocol_handler_lobby_handler_proto_msgTypes,
	}.Build()
	File_protocol_handler_lobby_handler_proto = out.File
	file_protocol_handler_lobby_handler_proto_goTypes = nil
	file_protocol_handler_lobby_handler_proto_depIdxs = nil
}
