package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

type routeItem struct {
	CmdID      string
	ServerType string // uint32 literal
	Service    string
	Method     string
	Route      string
	RspCmdID   string
	NoAuth     bool
}

var (
	serviceStartRE = regexp.MustCompile(`(?m)^\s*service\s+(\w+)\s*\{`)
	messageStartRE = regexp.MustCompile(`(?m)^\s*message\s+(\w+)\s*\{`)
	rpcRE          = regexp.MustCompile(`rpc\s+(\w+)\s*\(([\w.]+)\)\s*returns\s*\(([\w.]+)\)`)
	cmdIDRE        = regexp.MustCompile(`option\s*\(protocol\.common\.cmd_id\)\s*=\s*(\d+)\s*;`)
	noAuthRE       = regexp.MustCompile(`option\s*\(protocol\.common\.no_auth\)\s*=\s*true\s*;`)
	kindRE         = regexp.MustCompile(`option\s*\(protocol\.common\.kind\)\s*=\s*(\w+)\s*;`)
	serverTypeRE   = regexp.MustCompile(`option\s*\(protocol\.common\.server_type\)\s*=\s*(\w+)\s*;`)
)

func main() {
	var protoDir, out string
	flag.StringVar(&protoDir, "proto", "protocol/handler", "proto directory")
	flag.StringVar(&out, "out", "protocol/gen/routes.go", "output file")
	flag.Parse()

	routes, err := scanRoutes(protoDir)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	if err := os.WriteFile(out, []byte(renderRoutes(routes)), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func scanRoutes(dir string) ([]routeItem, error) {
	files, err := filepath.Glob(filepath.Join(dir, "*.proto"))
	if err != nil {
		return nil, err
	}
	var items []routeItem
	for _, path := range files {
		b, err := os.ReadFile(path)
		if err != nil {
			return nil, err
		}
		text := string(b)
		messages, err := extractBlocks(text, messageStartRE)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", path, err)
		}
		services, err := extractBlocks(text, serviceStartRE)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", path, err)
		}
		for name, body := range services {
			if firstMatch(kindRE, body) != "FRONTEND" {
				continue
			}
			serverType := firstMatch(serverTypeRE, body)
			if serverType == "" {
				continue
			}
			for _, rpcMatch := range rpcRE.FindAllStringSubmatch(body, -1) {
				rpcName := rpcMatch[1]
				input := rpcMatch[2]
				output := rpcMatch[3]
				inputMsg, ok := messages[input]
				if !ok {
					continue
				}
				cmdID := firstMatch(cmdIDRE, inputMsg)
				if cmdID == "" || cmdID == "0" {
					continue
				}
				rspCmdID := "0"
				if output != "google.protobuf.Empty" {
					if outputMsg, ok := messages[output]; ok {
						if id := firstMatch(cmdIDRE, outputMsg); id != "" {
							rspCmdID = id
						}
					}
				}
				items = append(items, routeItem{
					CmdID:      cmdID,
					ServerType: serverTypeToVal(serverType),
					Service:    name,
					Method:     rpcName,
					Route:      name + "/" + rpcName,
					RspCmdID:   rspCmdID,
					NoAuth:     noAuthRE.MatchString(inputMsg),
				})
			}
		}
	}
	seen := make(map[string]bool)
	for _, it := range items {
		if seen[it.CmdID] {
			return nil, fmt.Errorf("cmd_id %s is duplicated", it.CmdID)
		}
		seen[it.CmdID] = true
	}
	sort.Slice(items, func(i, j int) bool { return items[i].CmdID < items[j].CmdID })
	return items, nil
}

func extractBlocks(text string, startRE *regexp.Regexp) (map[string]string, error) {
	matches := startRE.FindAllStringSubmatchIndex(text, -1)
	out := make(map[string]string, len(matches))
	for _, m := range matches {
		if len(m) < 4 {
			continue
		}
		name := text[m[2]:m[3]]
		open := m[1] - 1
		if open < 0 || open >= len(text) || text[open] != '{' {
			return nil, fmt.Errorf("block %s missing opening brace", name)
		}
		close, err := matchBrace(text, open)
		if err != nil {
			return nil, fmt.Errorf("block %s: %w", name, err)
		}
		out[name] = text[open+1 : close]
	}
	return out, nil
}

func matchBrace(text string, open int) (int, error) {
	depth := 0
	for i := open; i < len(text); i++ {
		switch text[i] {
		case '{':
			depth++
		case '}':
			depth--
			if depth == 0 {
				return i, nil
			}
		}
	}
	return 0, fmt.Errorf("unmatched brace")
}

func firstMatch(re *regexp.Regexp, s string) string {
	m := re.FindStringSubmatch(s)
	if len(m) < 2 {
		return ""
	}
	return m[1]
}

func serverTypeToVal(name string) string {
	switch strings.TrimSpace(name) {
	case "ST_GATESVR":
		return "1"
	case "ST_LOBBYSVR":
		return "2"
	case "ST_ROOMSVR":
		return "3"
	case "ST_MATCHSVR":
		return "4"
	case "ST_ONLINESVR":
		return "5"
	case "ST_ROUTERAGENT":
		return "6"
	default:
		return "0"
	}
}

func routeConstName(serviceName, methodName string) string {
	return "Route" + serviceName + methodName
}

func renderRoutes(routes []routeItem) string {
	var b strings.Builder
	b.WriteString("// Code generated by tools/gen_routes. DO NOT EDIT.\n")
	b.WriteString("package rpc\n\n")
	b.WriteString("// RouteEntry 描述一条已生成的路由。\n")
	b.WriteString("type RouteEntry struct {\n")
	b.WriteString("\tCmdID      uint32\n")
	b.WriteString("\tServerType uint32\n")
	b.WriteString("\tRoute      string\n")
	b.WriteString("\tRspCmdID   uint32\n")
	b.WriteString("}\n\n")
	b.WriteString("const (\n")
	for _, r := range routes {
		b.WriteString(fmt.Sprintf("\t%s = %q\n", routeConstName(r.Service, r.Method), r.Route))
	}
	b.WriteString(")\n\n")
	b.WriteString("// RouteTable 客户端入口路由表。\n")
	b.WriteString("var RouteTable = map[uint32]RouteEntry{\n")
	for _, r := range routes {
		b.WriteString(fmt.Sprintf("\t%s: {CmdID: %s, ServerType: %s, Route: %s, RspCmdID: %s},\n",
			r.CmdID, r.CmdID, r.ServerType, routeConstName(r.Service, r.Method), r.RspCmdID))
	}
	b.WriteString("}\n\n")
	b.WriteString("// AuthWhitelist 免鉴权的 CmdID 集合。\n")
	b.WriteString("var AuthWhitelist = map[uint32]bool{\n")
	for _, r := range routes {
		if r.NoAuth {
			b.WriteString(fmt.Sprintf("\t%s: true,\n", r.CmdID))
		}
	}
	b.WriteString("}\n")
	return b.String()
}
