sock_path: "${routeragent_sock_path}"
listen_addr: "${routeragent_listen_addr}"
heartbeat_sec: 30

logger_group:
  main:
    level: info
    format: console
    stderr_also: true
    dir: "${log_dir}"
    basename: routeragent
    max_size_mb: 100
    max_backups: 72
    rotate_by_hour: true
  res:
    level: info
    format: console
    stderr_also: true
    dir: "${log_dir}"
    basename: routeragent_res
    max_size_mb: 100
    max_backups: 72
    rotate_by_hour: true
  tracing:
    level: info
    format: console
    stderr_also: true
    dir: "${log_dir}"
    basename: routeragent_tracing
    max_size_mb: 100
    max_backups: 72
    rotate_by_hour: true
