// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: protocol/common/options.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceKind int32

const (
	ServiceKind_FRONTEND ServiceKind = 0
	ServiceKind_BACKEND  ServiceKind = 1
)

// Enum value maps for ServiceKind.
var (
	ServiceKind_name = map[int32]string{
		0: "FRONTEND",
		1: "BACKEND",
	}
	ServiceKind_value = map[string]int32{
		"FRONTEND": 0,
		"BACKEND":  1,
	}
)

func (x ServiceKind) Enum() *ServiceKind {
	p := new(ServiceKind)
	*p = x
	return p
}

func (x ServiceKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceKind) Descriptor() protoreflect.EnumDescriptor {
	return file_protocol_common_options_proto_enumTypes[0].Descriptor()
}

func (ServiceKind) Type() protoreflect.EnumType {
	return &file_protocol_common_options_proto_enumTypes[0]
}

func (x ServiceKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceKind.Descriptor instead.
func (ServiceKind) EnumDescriptor() ([]byte, []int) {
	return file_protocol_common_options_proto_rawDescGZIP(), []int{0}
}

type ServerType int32

const (
	ServerType_ST_UNKNOWN     ServerType = 0
	ServerType_ST_GATESVR     ServerType = 1
	ServerType_ST_LOBBYSVR    ServerType = 2
	ServerType_ST_ROOMSVR     ServerType = 3
	ServerType_ST_MATCHSVR    ServerType = 4
	ServerType_ST_ONLINESVR   ServerType = 5
	ServerType_ST_ROUTERAGENT ServerType = 6
)

// Enum value maps for ServerType.
var (
	ServerType_name = map[int32]string{
		0: "ST_UNKNOWN",
		1: "ST_GATESVR",
		2: "ST_LOBBYSVR",
		3: "ST_ROOMSVR",
		4: "ST_MATCHSVR",
		5: "ST_ONLINESVR",
		6: "ST_ROUTERAGENT",
	}
	ServerType_value = map[string]int32{
		"ST_UNKNOWN":     0,
		"ST_GATESVR":     1,
		"ST_LOBBYSVR":    2,
		"ST_ROOMSVR":     3,
		"ST_MATCHSVR":    4,
		"ST_ONLINESVR":   5,
		"ST_ROUTERAGENT": 6,
	}
)

func (x ServerType) Enum() *ServerType {
	p := new(ServerType)
	*p = x
	return p
}

func (x ServerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerType) Descriptor() protoreflect.EnumDescriptor {
	return file_protocol_common_options_proto_enumTypes[1].Descriptor()
}

func (ServerType) Type() protoreflect.EnumType {
	return &file_protocol_common_options_proto_enumTypes[1]
}

func (x ServerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServerType.Descriptor instead.
func (ServerType) EnumDescriptor() ([]byte, []int) {
	return file_protocol_common_options_proto_rawDescGZIP(), []int{1}
}

var file_protocol_common_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*ServiceKind)(nil),
		Field:         50001,
		Name:          "protocol.common.kind",
		Tag:           "varint,50001,opt,name=kind,enum=protocol.common.ServiceKind",
		Filename:      "protocol/common/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*ServerType)(nil),
		Field:         50002,
		Name:          "protocol.common.server_type",
		Tag:           "varint,50002,opt,name=server_type,enum=protocol.common.ServerType",
		Filename:      "protocol/common/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*uint32)(nil),
		Field:         50003,
		Name:          "protocol.common.cmd_id",
		Tag:           "varint,50003,opt,name=cmd_id",
		Filename:      "protocol/common/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50004,
		Name:          "protocol.common.no_auth",
		Tag:           "varint,50004,opt,name=no_auth",
		Filename:      "protocol/common/options.proto",
	},
}

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional protocol.common.ServiceKind kind = 50001;
	E_Kind = &file_protocol_common_options_proto_extTypes[0]
	// optional protocol.common.ServerType server_type = 50002;
	E_ServerType = &file_protocol_common_options_proto_extTypes[1]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional uint32 cmd_id = 50003;
	E_CmdId = &file_protocol_common_options_proto_extTypes[2]
	// optional bool no_auth = 50004;
	E_NoAuth = &file_protocol_common_options_proto_extTypes[3]
)

var File_protocol_common_options_proto protoreflect.FileDescriptor

const file_protocol_common_options_proto_rawDesc = "" +
	"\n" +
	"\x1dprotocol/common/options.proto\x12\x0fprotocol.common\x1a google/protobuf/descriptor.proto*(\n" +
	"\vServiceKind\x12\f\n" +
	"\bFRONTEND\x10\x00\x12\v\n" +
	"\aBACKEND\x10\x01*\x84\x01\n" +
	"\n" +
	"ServerType\x12\x0e\n" +
	"\n" +
	"ST_UNKNOWN\x10\x00\x12\x0e\n" +
	"\n" +
	"ST_GATESVR\x10\x01\x12\x0f\n" +
	"\vST_LOBBYSVR\x10\x02\x12\x0e\n" +
	"\n" +
	"ST_ROOMSVR\x10\x03\x12\x0f\n" +
	"\vST_MATCHSVR\x10\x04\x12\x10\n" +
	"\fST_ONLINESVR\x10\x05\x12\x12\n" +
	"\x0eST_ROUTERAGENT\x10\x06:S\n" +
	"\x04kind\x12\x1f.google.protobuf.ServiceOptions\x18ц\x03 \x01(\x0e2\x1c.protocol.common.ServiceKindR\x04kind:_\n" +
	"\vserver_type\x12\x1f.google.protobuf.ServiceOptions\x18҆\x03 \x01(\x0e2\x1b.protocol.common.ServerTypeR\n" +
	"serverType:8\n" +
	"\x06cmd_id\x12\x1f.google.protobuf.MessageOptions\x18ӆ\x03 \x01(\rR\x05cmdId::\n" +
	"\ano_auth\x12\x1f.google.protobuf.MessageOptions\x18Ԇ\x03 \x01(\bR\x06noAuthB Z\x1eproject/protocol/common;commonb\x06proto3"

var (
	file_protocol_common_options_proto_rawDescOnce sync.Once
	file_protocol_common_options_proto_rawDescData []byte
)

func file_protocol_common_options_proto_rawDescGZIP() []byte {
	file_protocol_common_options_proto_rawDescOnce.Do(func() {
		file_protocol_common_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_common_options_proto_rawDesc), len(file_protocol_common_options_proto_rawDesc)))
	})
	return file_protocol_common_options_proto_rawDescData
}

var file_protocol_common_options_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_protocol_common_options_proto_goTypes = []any{
	(ServiceKind)(0),                    // 0: protocol.common.ServiceKind
	(ServerType)(0),                     // 1: protocol.common.ServerType
	(*descriptorpb.ServiceOptions)(nil), // 2: google.protobuf.ServiceOptions
	(*descriptorpb.MessageOptions)(nil), // 3: google.protobuf.MessageOptions
}
var file_protocol_common_options_proto_depIdxs = []int32{
	2, // 0: protocol.common.kind:extendee -> google.protobuf.ServiceOptions
	2, // 1: protocol.common.server_type:extendee -> google.protobuf.ServiceOptions
	3, // 2: protocol.common.cmd_id:extendee -> google.protobuf.MessageOptions
	3, // 3: protocol.common.no_auth:extendee -> google.protobuf.MessageOptions
	0, // 4: protocol.common.kind:type_name -> protocol.common.ServiceKind
	1, // 5: protocol.common.server_type:type_name -> protocol.common.ServerType
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	4, // [4:6] is the sub-list for extension type_name
	0, // [0:4] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protocol_common_options_proto_init() }
func file_protocol_common_options_proto_init() {
	if File_protocol_common_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_common_options_proto_rawDesc), len(file_protocol_common_options_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 4,
			NumServices:   0,
		},
		GoTypes:           file_protocol_common_options_proto_goTypes,
		DependencyIndexes: file_protocol_common_options_proto_depIdxs,
		EnumInfos:         file_protocol_common_options_proto_enumTypes,
		ExtensionInfos:    file_protocol_common_options_proto_extTypes,
	}.Build()
	File_protocol_common_options_proto = out.File
	file_protocol_common_options_proto_goTypes = nil
	file_protocol_common_options_proto_depIdxs = nil
}
