syntax = "proto3";

package protocol.common;

import "google/protobuf/descriptor.proto";

option go_package = "project/protocol/common;common";

enum ServiceKind {
  FRONTEND = 0;
  BACKEND = 1;
}

enum ServerType {
  ST_UNKNOWN      = 0;
  ST_GATESVR      = 1;
  ST_LOBBYSVR     = 2;
  ST_ROOMSVR      = 3;
  ST_MATCHSVR     = 4;
  ST_ONLINESVR    = 5;
  ST_ROUTERAGENT  = 6;
}

extend google.protobuf.ServiceOptions {
  ServiceKind kind = 50001;
  ServerType server_type = 50002;
}

extend google.protobuf.MessageOptions {
  uint32 cmd_id = 50003;
  bool no_auth = 50004;
}
